services:
  dns_update:
    image: iloveitaly/dreamhost-dns-updater:latest
    restart: unless-stopped
    environment:
      - SCHEDULE="@hourly"
      - DREAMHOST_UPDATE_DOMAIN="node.domain.com"
      - DREAMHOST_API_KEY="key"
